version: 2

references:
  test-steps: &test-steps
    steps:
      - checkout
      - run:
          name: libxmlsec1 dependency
          command: sudo apt-get update -y && sudo apt-get install -y libxmlsec1-dev
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run: poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run: poetry run pytest --black --cov=tbk


jobs:
  tests-37:
    docker:
      - image: circleci/python:3.7
    <<: *test-steps


  tests-38:
    docker:
      - image: circleci/python:3.8-rc
    <<: *test-steps

  tests-36:
    docker:
      - image: circleci/python:3.6
    <<: *test-steps

  tests-27:
    docker:
      - image: circleci/python:2.7
    <<: *test-steps

  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: pip install --user toml
      - run: ls
      - run: poetry build -f wheel
      - persist_to_workspace:
          root: ~/
          paths: dist

  pipinstall-py27:
    docker:
      - image: circleci/python:2.7
    steps:
      - run:
          name: libxmlsec1 dependency
          command: sudo apt-get update -y && sudo apt-get install -y libxmlsec1-dev
      - attach_workspace:
          at: ~/
      - run: pip install dist/*.whl
      - run: python -c "import tbk; print(tbk.__version__)"

  pipinstall-py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          name: libxmlsec1 dependency
          command: sudo apt-get update -y && sudo apt-get install -y libxmlsec1-dev
      - attach_workspace:
          at: ~/
      - run: ls dist
      - run: pip install dist/*.whl
      - run: python -c "import tbk; print(tbk.__version__)"


workflows:
  version: 2

  tests:
    jobs:
      - tests-27
      - tests-36
      - tests-37
      - tests-38
  build:
    jobs:
      - build
      - pipinstall-py27:
          requires:
            - build
      - pipinstall-py37:
          requires:
            - build
